### ISSUE TITLE
Override root path

### ISSUE THREAD

**Issue by mjaneczek** [michaelzoidl/babel-root-import#1]
Hi!

Is there any way to override the root path? Basically, I have folder "src" and want to import directly from this folder.

Example:
```
// this works
import Test from '~/src/components/Test';

// want this
import Test from '~/components/Test';
```

**Comment by michaelzoidl** [comment]
Hi Michał, sorry didn't saw you issue.
Ya, had the same idea while i developed this, the easiest way would be some configuration-stuff in the .babelrc

I'm not sure i babel ships a API where i get those data - otherwise we could simple check if there's a babelrc and when, does it contain some basePath param.

Is this still an issue? If yes i could take care of this and implement it the next days

**Comment by mjaneczek** [comment]
@michaelzoidl No problem, I changed a way of importing and now it's not a big issue for me, so you can close this issue and maybe develop this feature in future if find a time. ;)

**Comment by michaelzoidl** [comment]
ok cool. :)
Have tracked it ... but thanks anyway for this feature-request

**Comment by yesmeck** [comment]
I need this, but I'm not familiar with writing babel plugin.

Plugin options are supported now, https://github.com/babel/babel/issues/2168 see `Plugin options` section.

**Comment by michaelzoidl** [comment]
Okay guys... this feature is now (from version `3.1.0`) implemented! Thanks to @degr.
