### ISSUE TITLE
[QUESTION] Get working with require()?

### ISSUE THREAD

**Issue by danawoodman** [michaelzoidl/babel-root-import#18]
Great plugin! So far this is my favorite solution to the `../../../../../../` require problem :smile: 

I had a question, would it be theoretically possible to also get this behavior with a CommonJS `require` import in addition to an `import`?

Would be nice to have this work in all situations if possible.

**Comment by michaelzoidl** [comment]
Hm.. interesting question, sounds like you already tested this case... 
Currently the plugin uses the "Import" API, maybe it's just to also support the "Require" API.

Currently i'm searching for this `../../../` thing a solution, but i take a look if this is possible / easy to do... 

Thanks for the input :)

**Comment by danawoodman** [comment]
Yeah I feel that it will be confusing if this behavior only works for `import` and not `require` (it was for me!). I imagine it wouldn't be a lot more to add that support but I'm not sure

**Comment by michaelzoidl** [comment]
Hey @danawoodman sorry for the late feedback, so - yea, the idea to support `require` is good, currently i've the problem to find the right time to implement this.

Since you're the first person who requested this and the most people want to implement the relative path creating i set my focus the this issue.

So to be clear: since i don't have time and i'm not planing to implement this (sorry) i will close this issue.
Maybe you find the time to make a PR :) 

Michael
